name: Testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  packages: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v4
        id: setup-gradle
        with:
          gradle-version: current

      - run: gradle test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Junit Tests
          path: '**/build/test-results/test/TEST*.xml'
          reporter: java-junit
          fail-on-error: true

      - run: gradle publish
        env:
          TOKEN: ${{ secrets.PKG_TOKEN }}