name: Testing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Run Gradle Test
        run: ./gradlew test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          artifact: test-results
          name: JUnit Tests
          path: '*.xml'
          reporter: java-junit
          fail-on-error: true